### ISSUE TITLE
Better parsing of app name from git remote

### ISSUE THREAD

**Issue by Qard** [flynn-archive/flynn-cli#1]
Currently, the app name parsing is completely tied to a vagrant@flynn:app-name structure, which doesn't really work when the user name isn't vagrant, and assumes a ssh host config, which probably shouldn't be required.

see: https://github.com/flynn/flynn-cli/blob/master/main.go#L145, https://github.com/flynn/flynn-cli/blob/master/git.go#L15

**Comment by titanous** [comment]
Yeah, this is hacked in for the flynn-dev demo, we definitely need something better.

**Comment by titanous** [comment]
This is fixed by the updated version.
