### ISSUE TITLE
Reduce the number of top-level flynn commands

### ISSUE THREAD

**Issue by sjama** [flynn-archive/flynn-cli#12]
I think we should refactor some top-level commands to use subcommands instead.

Here's rough outline of how it may look:

**log** - get a job log
**ps** - list jobs
**run** - run a job
**scale** - scale a job
**version** - print flynn-cli version

**app** - list current apps 
**app add** - add a new app 
**app remove** - remove an existing app

**env** - list current env's 
**env add** - add a new env 
**env remove** - remove an existing env's

**key** - list current keys 
**key add** - add a new key 
**key remove** - remove an existing key

**route** - list current routes 
**route add** - add a new routes (defaults to http, use -t to specify a different type)
**route remove** - remove an existing route

**provider** - list current providers 
**provider add** - add a new provider 
**provider remove** - remove an existing provider

**server** - list current servers 
**server add** - add a new server
**server remove** - remove an existing server

My main reasoning for reducing the number of top-level commands (**20 to 11**) is that it will help users more easily interact with flynn, this approach also follows the same strategy as used by other major projects like git or vagrant.

**Comment by jayd3e** [comment]
I like this idea a lot.  The only prob is flynn-cli is based off of https://github.com/heroku/hk, which doesn't really use subcommands, so it might be a little tricky to work this into things easily.  It might be something that's nice to have, but won't be feasible unless flynn-cli is re-architected.  Idk maybe I'm completely wrong.

**Comment by titanous** [comment]
@jayd3e It's totally doable.

@sjama Thanks! I'll review this tomorrow.

**Comment by jayd3e** [comment]
Cool! +1

**Comment by titanous** [comment]
This looks good overall. Here are a few modifications:

**app** - show details for the current app
**app list** - list apps

We should rename **server** to **cluster**, I made a mistake when naming it initially.

**resource** is missing, **env get** is missing.

**Comment by sjama** [comment]
@titanous "current app" seem's quite ambiguous to me. 
I think is better for the top-level command to do the "listing" without relying on a "list" subcommand. 

If you wish to target a specific app or key maybe a flag? 

**app** -n example-app
**key** -n my-key

Yep, somehow missed **resource**, I was replacing **env get** with just **env**. Again -n can be used to target a specific **env**.

Agreed! cluster is better description then server.

**Comment by ilovenwd** [comment]
+1 for titanous

app - show details for the current app
app list - list apps

**Comment by titanous** [comment]
At the same time we should consider switching to [docopt](https://github.com/docopt/docopt.go).
