### ISSUE TITLE
flynn server-add URL for Vagrant mode?

### ISSUE THREAD

**Issue by chriskilding** [flynn-archive/flynn-cli#14]
The docs don't give much help for configuring `flynn server-add` or `key-add`; if the server were external, this would be easier, but can you provide more instructions (or even a small script) for adding the Vagrant server to the Flynn client? In particular, if there is a default Vagrant server URL, what is it, and do we need to specify our public key twice (since `server-add` expects some form of key as an argument)?

Currently getting a lot of "controller not found" and "Post http://10.0.2.15/keys: dial tcp 10.0.2.15:80: connection refused" errors after tinkering with my ssh config and the flynnrc trying to set this up.

**Comment by titanous** [comment]
The provisioning output of the Vagrant box includes the `flynn server-add` command, did that not work?

**Comment by chriskilding** [comment]
FWIW it would be nice to use something like `flynnapp.com` as an alias rather than dealing with IP addresses.

**Comment by chriskilding** [comment]
Aha, now I see it - user error on my part :P is there any way to automatically execute that in the `vagrant up` command?

**Comment by titanous** [comment]
I don't think that's possible until mitchellh/vagrant#3849 happens.

**Comment by titanous** [comment]
The alias domain is a good idea, would you open an issue on flynn-demo suggesting it?

**Comment by chriskilding** [comment]
will do
