### ISSUE TITLE
Better error handling for logs command

### ISSUE THREAD

**Issue by Qard** [flynn-archive/flynn-cli#2]
If you supply no args it panics and if you give it an invalid name you get `Unexpected error: 404 Not Found`.

**Comment by titanous** [comment]
Do you want to submit a pull request fixing those issues?

**Comment by Qard** [comment]
Yep. I'm going to start looking at some of these tonight. Didn't have time
at the time of reporting, but didn't want to forget about it so I created
some issues.

**Comment by titanous** [comment]
Awesome!
