### ISSUE TITLE
Homebrew forumla

### ISSUE THREAD

**Issue by davidcelis** [flynn-archive/flynn-cli#6]
I would like to provide a formula for flynn-cli to [homebrew/homebrew](https://github.com/homebrew/homebrew) for an alternative OSX installation method but they require that formulae build the utility from source. I could submit the pre-built binary to [homebrew/homebrew-binary](https://github.com/homebrew/homebrew-binary) but it's unfortunately less discoverable.

The installation script seems to pull a binary based on the user-agent, but are there links to static, versioned source releases with build instructions for something like a homebrew formula?

**Comment by titanous** [comment]
Releases [are tagged](https://github.com/flynn/flynn-cli/releases) (there is an atom feed), and I'll add build instructions to the README. The preferred distribution option is via the official pre-built binaries as they contain an automatic updater that is invisible to the user and pulls down tiny binary patches (very similar to how Chrome updates minus the background service).

**Comment by titanous** [comment]
I should mention that the reason behind the automatic updates is that the project is moving fast and we don't want users to have to frequently install updates manually.

**Comment by titanous** [comment]
Added build instructions to the README.

**Comment by davidcelis** [comment]
Ah, if the binary contains an auto-updater than a formula to build from source probably isn't the best idea after all. I was wondering if the binary automatically updated, actually. Thanks for that clarification.

I'll see about contributing to homebrew-binary instead, or let the development of the CLI settle down a bit first.

**Comment by titanous** [comment]
Cool, let me know if you end up doing it. I'm not sure the updater will play nice with homebrew-binary since it expects installed binaries to stay static I think.
